name: Bug Report
description: I found a bug!
title: "🐛 ..."
type: Bug
body:
  - type: markdown
    attributes:
      value: ⚠️ Attention! We won't support macOS in a long time. Don't report bugs related to macOS here.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue you are facing.
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: System Info
      description: Select the system you are using.
      options:
        - Windows
        - macOS
        - Linux
        - Android
      default: 0
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: More information about the issue.
      placeholder: Drag and drop files to here.
    validations:
      required: false
