name: Bug 报告
description: 报告一个 Bug 或者漏洞
title: "Bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: agreements
    attributes:
      label: 我已阅读并同意以下条款
      description: 如果你没有认真阅读，你的 Issue 可能会被直接关闭！
      options:
        - label: 我已阅读 [FAQ](https://liren.zty012.de/project-graph/v2/faq)
          required: true
        - label: 我已尝试使用 [Nightly Build](https://github.com/LiRenTech/project-graph/releases/nightly)，并且没有解决我的问题
          required: true
        - label: 我已浏览 [Issues](https://github.com/LiRenTech/project-graph/issues) 并且没有找到类似的问题
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请详细描述一下你遇到的问题。
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 系统版本
      description: 请选择你使用的系统版本。
      options:
        - Windows
        - macOS
        - Debian based Linux (Debian, Ubuntu, Kali Linux, ...)
        - Arch based Linux (Arch Linux, Manjaro, ...)
      default: 0
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: 附件
      description: 如果可以的话，请附上出现问题的项目 json 文件或者截图。
      placeholder: 拖拽文件到此处
    validations:
      required: false
