name: Bug 报告
description: 我发现了一个 Bug！
title: "🐛 ..."
type: Bug
body:
  - type: markdown
    attributes:
      value: ⚠️ 注意！如果你要反馈的问题是“macOS 系统下 CPU 占用高”，我们已经知道这个问题，并且正在跟进。请不要反馈重复的问题！
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请详细描述一下你遇到的问题。
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 系统版本
      description: 请选择你使用的系统版本。
      options:
        - Windows
        - macOS
        - Linux
        - Android
      default: 0
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: 软件的版本
      description: 请提供软件的版本号信息
      placeholder: x.x.x
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: 附件
      description: 如果可以的话，请附上出现问题的项目 json 文件或者截图。
      placeholder: 拖拽文件到此处
    validations:
      required: false
