blank_issues_enabled: false
contact_links:
  - name: 加入 QQ 群
    url: https://qm.qq.com/cgi-bin/qm/qr?k=1Wskf2Y2KJz3ARpCgzi04y_p95a78Wku&jump_from=webapi&authKey=EkjB+oWihwZIfyqVsIv2dGrNv7bhSGSIULM3+ZLU2R5AVxOUKaIRwi6TKOHlT04/
    about: 如果是小问题，请加入 QQ 群咨询。
  - name: Join our Telegram Group
    url: https://t.me/@projectgraph
    about: If you have any questions, feel free to join our Telegram Group.
