name: 功能请求
description: 想要新的功能？对现有功能有疑问？请选择此模板。
title: "✨ ..."
type: Feature
body:
  - type: markdown
    attributes:
      value: ⚠️ 注意！你想要的功能可能已经被别人提出过了，请在 Issues 中搜索相关内容，避免重复提交！
  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请简要描述你希望应用具备的功能。
      placeholder: 例如：希望支持项目依赖关系图的可视化展示。
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: 附件
      description: 如果可以的话，请附上出现问题的工程文件或者截图。
      placeholder: 拖拽文件到此处
    validations:
      required: false
