name: 功能请求
description: 对 Project Graph 的功能请求
title: "Feature: "
labels: ["feature"]
body:
  - type: checkboxes
    id: agreements
    attributes:
      label: 我已阅读并同意以下条款
      description: 如果你没有认真阅读，你的 Issue 可能会被直接关闭！
      options:
        - label: 我已尝试使用 [Nightly Build](https://github.com/LiRenTech/project-graph/releases/nightly)，并且没有我想要的功能
          required: true
        - label: 我已浏览 [Issues](https://github.com/LiRenTech/project-graph/issues) 并且没有找到类似的功能请求
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请简要描述你希望 Project Graph 具备的功能。
      placeholder: 例如：希望支持项目依赖关系图的可视化展示。
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 请提供其他有助于理解或实现该功能的信息。
      placeholder: 例如：希望支持的格式可以是 Graphviz、PlantUML 等。
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: 附件
      description: 如果可以的话，请附上出现问题的项目 json 文件或者截图。
      placeholder: 拖拽文件到此处
    validations:
      required: false
